# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\VicMbugua\Projects\TaskManagementSystem\ui\project.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddProject(object):
    def setupUi(self, AddProject):
        AddProject.setObjectName("AddProject")
        AddProject.resize(300, 200)
        font = QtGui.QFont()
        font.setPointSize(10)
        AddProject.setFont(font)
        AddProject.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(AddProject)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, -1, 12)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.dialog_title = QtWidgets.QLabel(AddProject)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dialog_title.setFont(font)
        self.dialog_title.setObjectName("dialog_title")
        self.horizontalLayout_3.addWidget(self.dialog_title)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(AddProject)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.project_name = QtWidgets.QLineEdit(AddProject)
        self.project_name.setObjectName("project_name")
        self.horizontalLayout.addWidget(self.project_name)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.error_message = QtWidgets.QLabel(AddProject)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.error_message.setFont(font)
        self.error_message.setStyleSheet("color: red;")
        self.error_message.setAlignment(QtCore.Qt.AlignCenter)
        self.error_message.setObjectName("error_message")
        self.verticalLayout.addWidget(self.error_message)
        spacerItem2 = QtWidgets.QSpacerItem(20, 55, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.save_btn = QtWidgets.QPushButton(AddProject)
        self.save_btn.setFocusPolicy(QtCore.Qt.TabFocus)
        self.save_btn.setObjectName("save_btn")
        self.horizontalLayout_2.addWidget(self.save_btn)
        self.cancel_btn = QtWidgets.QPushButton(AddProject)
        self.cancel_btn.setFocusPolicy(QtCore.Qt.TabFocus)
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout_2.addWidget(self.cancel_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(AddProject)
        self.cancel_btn.clicked.connect(AddProject.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AddProject)

    def retranslateUi(self, AddProject):
        _translate = QtCore.QCoreApplication.translate
        AddProject.setWindowTitle(_translate("AddProject", "Add Project"))
        self.dialog_title.setText(_translate("AddProject", "Add Project"))
        self.label.setText(_translate("AddProject", "Project Name:"))
        self.error_message.setText(_translate("AddProject", "Error Message"))
        self.save_btn.setText(_translate("AddProject", "Save"))
        self.cancel_btn.setText(_translate("AddProject", "Cancel"))
