# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\VicMbugua\Projects\TaskManagementSystem\ui\subtasks.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SubtaskWindow(object):
    def setupUi(self, SubtaskWindow):
        SubtaskWindow.setObjectName("SubtaskWindow")
        SubtaskWindow.resize(554, 376)
        SubtaskWindow.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(SubtaskWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, -1, 12)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.task_name = QtWidgets.QLabel(SubtaskWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.task_name.sizePolicy().hasHeightForWidth())
        self.task_name.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.task_name.setFont(font)
        self.task_name.setObjectName("task_name")
        self.horizontalLayout_3.addWidget(self.task_name)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, -1, 12)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(SubtaskWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.subtask_name = QtWidgets.QLineEdit(SubtaskWindow)
        self.subtask_name.setObjectName("subtask_name")
        self.horizontalLayout_2.addWidget(self.subtask_name)
        self.add_subtask_btn = QtWidgets.QPushButton(SubtaskWindow)
        self.add_subtask_btn.setObjectName("add_subtask_btn")
        self.horizontalLayout_2.addWidget(self.add_subtask_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(SubtaskWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.subtasks_table = QtWidgets.QTableView(SubtaskWindow)
        self.subtasks_table.setTabKeyNavigation(False)
        self.subtasks_table.setObjectName("subtasks_table")
        self.verticalLayout.addWidget(self.subtasks_table)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(272, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.cancel_btn = QtWidgets.QPushButton(SubtaskWindow)
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout.addWidget(self.cancel_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(SubtaskWindow)
        self.cancel_btn.clicked.connect(SubtaskWindow.close) # type: ignore
        self.subtask_name.returnPressed.connect(self.add_subtask_btn.click) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SubtaskWindow)

    def retranslateUi(self, SubtaskWindow):
        _translate = QtCore.QCoreApplication.translate
        SubtaskWindow.setWindowTitle(_translate("SubtaskWindow", "Subtasks"))
        self.task_name.setText(_translate("SubtaskWindow", "Task Name"))
        self.label.setText(_translate("SubtaskWindow", "Enter Subtask Name"))
        self.add_subtask_btn.setText(_translate("SubtaskWindow", "Add SubTask"))
        self.label_2.setText(_translate("SubtaskWindow", "Subtasks List:"))
        self.cancel_btn.setText(_translate("SubtaskWindow", "Cancel"))
